### Get posts 
GET http://localhost:3001

### Login with valid credentials 
POST http://localhost:3001/user/login
Content-Type: application/json

{ "users_email":"user1@example.com", 
"users_password":"password" }

### Login with invalid credentials 
POST http://localhost:3001/user/login 
Content-Type: application/json

{ "users_email":"user@example.com", 
  "users_password":"wrongpassword"
   }

### Registration 
POST http://localhost:3001/user/register 
Content-Type: application/json

{
  "users_email": "user1@example.com",
  "users_password": "password"
}
### Review listing
GET  http://localhost:3001/reviews
Content-Type: application /json

[
  {
    "review_id": 1,
    "review_rating": 5,
    "review_text": "This movie was fantastic!",
    "review_created_at": "2024-11-13T08:14:39.966Z",
    "review_users_id": 1,
    "movie_id": 1,
    "movie_image": "https://example.com/inception.jpg",
    "movie_title": "Inception",
    "movie_description": "A mind-bending thriller where dreams and reality blur."
  }
]


### Get userspage
GET http://localhost:3001/userpage/?users_id=1
Content-Type: application/json
