### Get posts 
GET http://localhost:3001

### Login with valid credentials 
POST http://localhost:3001/user/login
Content-Type: application/json

{ "users_email":"user1@example.com", 
"users_password":"password" }

### Login with invalid credentials 
POST http://localhost:3001/user/login 
Content-Type: application/json

{ "users_email":"user@example.com", 
  "users_password":"wrongpassword"
   }

### Registration 
POST http://localhost:3001/user/register 
Content-Type: application/json

{
  "users_email": "user1@example.com",
  "users_password": "password"
}

### Review listing
GET  http://localhost:3001/reviews
Content-Type: application /json

{
  "review_rating": 5,
  "review_text": "This movie was fantastic!",
  "review_created_at": "2024-11-13T08:14:39.966Z",
  "review_users_id": "1",
  "review_movie_id": "2435",
  "review_users_email": "mike.milson@gmail.com"
}

### Listing a single review
GET http://localhost:3001/reviews/review
Content-Type: application /json

{
  "review_rating": 5,
  "review_text": "This movie was fantastic!",
  "review_created_at": "2024-11-13T08:14:39.966Z",
  "review_users_id": "1",
  "review_movie_id": "2435",
  "review_users_email": "mike.milson@gmail.com"
}

### Review creation
POST http://localhost:3001/reviews/create
Content-Type: application /json

{
  "review_users_id": "1" ,
  "review_users_email": "mike.milson@gmail.com" ,
  "review_movie_id": "2435",
  "review_text": "This movie was epic",
  "review_rating": "5",
  "review_created_at": "2024-11-13T08:14:39.966Z" 
}



### Get userspage
GET http://localhost:3001/userpage/?users_id=1
Content-Type: application/json

### Test adding a favorite
POST http://localhost:3001/movie/addFavorite/
Content-Type: application/json

{
    "users_id": 1,
    "movie_id": 12
}